/**
 * routes/deepinfra.js — the one place a paid cloud generation actually happens (MPI-851).
 *
 * The renderer cannot make this call itself, and must not: the API key lives in the main
 * process and there is no channel that hands it out (set / has / clear only, by design).
 * So the renderer asks for a generation by MODEL ID and this route resolves everything
 * else — which endpoint, which key, which body. Taking the endpoint id from the client
 * would let any renderer path spend the user's money at any model on DeepInfra's
 * catalogue; taking the model id means the ModelDef is the whitelist.
 *
 * THE NATIVE ROUTE, NOT THE OPENAI-COMPATIBLE ONE. `POST /v1/inference/<model>` returns
 * `inference_status.cost` — the true figure for this call. The OpenAI-shaped routes
 * return `created` and `data` and nothing else, so dispatching there would lose the cost
 * entirely and leave the spend readout summing estimates.
 *
 * BYTES, NOT A LINK. DeepInfra hands images back as base64 (and video as a URL), while
 * `save-generation` wants something it can stream and derives the file extension from a
 * `?filename=`. So the bytes land in a scratch file here and the response points at
 * `GET /deepinfra/output/:id`, which is a real http URL with a real extension — the save
 * path is then completely unchanged. It matters that the extension is right rather than
 * assumed: the same family returns JPEG on one tier and PNG on another.
 *
 * WHAT NEVER LEAVES THIS FILE: the key, and the upstream response body. A DeepInfra
 * error body can carry account detail, and `routes/secretRedaction.js` is five regexes
 * for key-shaped strings — it cannot scrub a name or an address. So failures are
 * answered as a CODE plus a message this file wrote, and nothing upstream reaches
 * `logger.*`, which is exfiltratable by design.
 *
 *   POST /deepinfra/generate  { modelId, operation, prompt, seed, width, height,
 *                               ratioLabel, qualityTier, duration, imagePaths, batch,
 *                               estimateUsd }
 *     -> { ok:true, viewUrls:[…], cost:{ usd, model, at }, seed }
 *        The size arrives in every currency the caller knows and `buildSizeFields`
 *        picks the one THIS endpoint takes — pixels, a 'WIDTHxHEIGHT' string, a bare
 *        ratio label, or a resolution tier plus a ratio plus a duration. `batch` is the
 *        provider's own native count where it has one (`num_images`, or Veo's
 *        `sample_count`): N outputs, ONE call, ONE bill.
 *     -> { ok:false, error:{ code, message } }   NO_KEY | NO_PROFILE | NO_CREDIT |
 *                                                CONTENT_FILTERED | PROVIDER_ERROR |
 *                                                LOW_BALANCE | OVER_LIMIT (refused
 *                                                before dispatch; message carries the figures)
 *   GET  /deepinfra/output/:id  -> the generated bytes; kept 24 h, then swept.
 *   GET  /deepinfra/account     -> this month's spend and both stops (MPI-855), numbers only.
 */

'use strict';

const express = require('express');
const fs = require('fs-extra');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const sharp = require('sharp');
const router = express.Router();
const logger = require('./logger');
const { ask } = require('./forkBridge');
const { MODELS } = require('../js/data/modelConstants/models.js');
const { buildSizeFields, batchFieldFor } = require('../js/data/modelConstants/deepinfraSizing.js');
const { buildCollage } = require('./deepinfraCollage');
const { getCommand } = require('../js/data/commandRegistry.js');

const PROFILE_ID = 'deepinfra';
const INFERENCE_BASE = 'https://api.deepinfra.com/v1/inference';
// Long, because a 1080p video clip legitimately takes minutes — but finite, because a
// Node fetch gives up at 300 s waiting for HEADERS whatever an AbortSignal says, and a
// silent hang would hold the cloud lane open forever.
const REQUEST_TIMEOUT_MS = 280000;
const ACCOUNT_BASE = 'https://api.deepinfra.com';
const ACCOUNT_TIMEOUT_MS = 5000;

// `services/llmEngines.mjs` is ESM and this router is CJS — same dynamic-import bridge
// routes/llm.js uses, and the same `resolveConnection` behind it, so there is exactly
// one key resolution in the app.
let _enginesPromise = null;
function engines() {
    if (!_enginesPromise) _enginesPromise = import('../services/llmEngines.mjs');
    return _enginesPromise;
}

/** Scratch dir for generated bytes on their way into a project. */
const OUTPUT_DIR = path.join(os.tmpdir(), 'cubric-deepinfra');
// These bytes were PAID for. Serving one proves nothing about the project copy — the
// save can still fail after the last byte leaves (disk full, project moved) — so a file
// is never removed on serve, only once it is old enough that any save has long finished.
const OUTPUT_KEEP_MS = 24 * 60 * 60 * 1000;

/** Remove scratch outputs older than OUTPUT_KEEP_MS. Best effort; never throws. */
async function _sweepOutputs(dir = OUTPUT_DIR, now = Date.now()) {
    const names = await fs.readdir(dir).catch(() => []);
    for (const name of names) {
        const file = path.join(dir, name);
        const stat = await fs.stat(file).catch(() => null);
        if (stat?.isFile() && now - stat.mtimeMs > OUTPUT_KEEP_MS) await fs.remove(file).catch(() => {});
    }
}

const _fail = (res, code, message, status = 200) =>
    res.status(status).json({ ok: false, error: { code, message } });

/**
 * Map an upstream status (and its `detail`, read here and nowhere else) to a code the UI
 * has copy for. Never echo the body. Measured 2026-09-25 (MPI-919):
 *   - a Gemini refusal is a 500, detail "<model> returned no image data";
 *   - a request WE malformed is a 422 (pydantic field validation), or a 500 whose detail
 *     wraps the provider's own 4xx: "Request to <url> failed with status: 400, ...".
 * Calling the second kind "the model refused" sent users rewording prompts at our bug.
 */
function _codeForStatus(status, detail = '') {
    if (status === 401 || status === 403) return 'NO_KEY';
    if (status === 402) return 'NO_CREDIT';
    if (status === 422) return 'PROVIDER_ERROR';
    if (_wrappedStatus(detail) && !/safety|block|prohibit|policy/i.test(detail)) return 'PROVIDER_ERROR';
    // The Gemini family answers a refused prompt with a 500 and no image. It is a
    // frequent path for this product's material, not an edge case.
    if (status === 400 || status === 500) return 'CONTENT_FILTERED';
    return 'PROVIDER_ERROR';
}

/** The provider's own 4xx wrapped inside a DeepInfra error detail, or null. */
function _wrappedStatus(detail) {
    const m = /failed with status: (4\d\d)/.exec(String(detail || ''));
    return m ? Number(m[1]) : null;
}

/**
 * What the account can still spend, from `/payment/checklist` (MPI-869). `/payment/config`
 * carries only `limit` — no balance — so this is the one endpoint that has the money.
 * THAT BODY ALSO CARRIES THE BILLING ADDRESS AND CARD LAST4: only the numeric fields below
 * are ever read out of it, and nothing of it is logged or returned.
 *
 * Prepaid (`billing_type: 'balance'`): Stripe's customer balance is NEGATIVE when it holds
 * credit, and `recent` is this month's usage not yet drawn from it, so what is left is
 * `-stripe_balance - recent`. An auto top-up account refills, so it has no balance stop.
 * `limit` is the cap the user set on a month's spend, whatever the balance; `recent` is what
 * counts against it. Both matched the dashboard to the cent on 2026-09-24: PREPAID CREDITS
 * $1.54, MONTHLY USAGE $2.90 / $5.00 LIMIT.
 *
 * @returns {{balanceUsd:number|null, limitRoomUsd:number|null}}  null = no such stop.
 */
function _accountRoom(checklist) {
    const num = v => (typeof v === 'number' && Number.isFinite(v) ? v : null);
    const recent = num(checklist?.recent) ?? 0;
    const credit = num(checklist?.stripe_balance);
    const limit = num(checklist?.limit);
    const prepaid = checklist?.billing_type === 'balance' && !checklist?.topup && credit !== null;
    return {
        balanceUsd: prepaid ? -credit - recent : null,
        limitRoomUsd: limit !== null && limit > 0 ? limit - recent : null,
    };
}

/**
 * Refuse a run the account cannot pay for, BEFORE it is sent (MPI-869). The provider's own
 * 402 stays the backstop: this answers null (let it through) whenever the account cannot be
 * read, because a slow billing page must never block a run that would have succeeded.
 *
 * @returns {{code:string, message:string}|null}
 */
function _creditRefusal(estimateUsd, room) {
    if (!(estimateUsd > 0) || !room) return null;
    const usd = v => `$${Math.max(0, v).toFixed(2)}`;
    if (room.balanceUsd !== null && estimateUsd > room.balanceUsd) {
        return { code: 'LOW_BALANCE', message: `Not enough DeepInfra credit: this costs about ${usd(estimateUsd)} and your balance has ${usd(room.balanceUsd)} left. Top up at deepinfra.com — nothing was sent and nothing was billed.` };
    }
    if (room.limitRoomUsd !== null && estimateUsd > room.limitRoomUsd) {
        return { code: 'OVER_LIMIT', message: `This would pass your DeepInfra monthly limit: it costs about ${usd(estimateUsd)} and ${usd(room.limitRoomUsd)} of the limit is left this month. Raise the limit at deepinfra.com — nothing was sent and nothing was billed.` };
    }
    return null;
}

/**
 * The Remote panel's readout (MPI-855): this month's spend plus both stops, as four named
 * numbers built here. Same rule as `_accountRoom` — the checklist body carries the billing
 * address and card last4, so nothing is copied out of it wholesale.
 */
function _accountSummary(checklist) {
    const num = v => (typeof v === 'number' && Number.isFinite(v) ? v : null);
    const limit = num(checklist?.limit);
    return {
        spentUsd: num(checklist?.recent) ?? 0,
        ..._accountRoom(checklist),
        limitUsd: limit !== null && limit > 0 ? limit : null,
    };
}

/** The checklist body, or null. Never logged, never returned — callers pick numbers from it. */
async function _readChecklist(key) {
    try {
        const r = await fetch(`${ACCOUNT_BASE}/payment/checklist`, {
            headers: { Authorization: `bearer ${key}` },
            signal: AbortSignal.timeout(ACCOUNT_TIMEOUT_MS),
        });
        return r.ok ? await r.json() : null;
    } catch (_) {
        return null;
    }
}

async function _readAccountRoom(key) {
    const checklist = await _readChecklist(key);
    return checklist ? _accountRoom(checklist) : null;
}

/**
 * Every output the model answered with: a data URL, bare base64, or an https link. The
 * field AND the form differ per model (every shipped endpoint's schema_out, 2026-09-25):
 * the Gemini family and FLUX-2 dev answer base64 in `images`, Seedream answers LINKS in
 * `images`, FLUX-2 pro/max one `image_url` link, Seedance and Wan a `video_url` link,
 * Veo a `videos` list.
 */
function _outputsOf(body) {
    const one = body?.video_url || body?.output?.video_url || body?.image_url;
    const list = one ? [one]
        : body?.videos || body?.images || body?.image || body?.output
            || (Array.isArray(body?.data) ? body.data.map(d => d?.b64_json) : null) || [];
    return [].concat(list).filter(raw => typeof raw === 'string' && raw);
}

/** The bytes behind one output: fetched when it is a link, decoded when it is base64. */
async function _bytesOf(raw) {
    if (/^https?:\/\//i.test(raw)) {
        const r = await fetch(raw, { signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS) });
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return Buffer.from(await r.arrayBuffer());
    }
    const dataUri = /^data:[^;,]+;base64,/i.exec(raw);
    return Buffer.from(dataUri ? raw.slice(dataUri[0].length) : raw, 'base64');
}

const IMAGE_MIME = { jpg: 'image/jpeg', png: 'image/png', webp: 'image/webp' };

/**
 * The file's extension from its magic bytes, or null for anything else. Never trust a
 * label: the first real generation came back as JPEG bytes in a field that implied PNG.
 */
function _extOf(buf) {
    if (buf.slice(0, 3).toString('hex') === 'ffd8ff') return 'jpg';
    if (buf.slice(0, 4).toString('hex') === '89504e47') return 'png';
    if (buf.slice(0, 4).toString('ascii') === 'RIFF' && buf.slice(8, 12).toString('ascii') === 'WEBP') return 'webp';
    if (buf.slice(4, 8).toString('ascii') === 'ftyp') return 'mp4';
    if (buf.slice(0, 4).toString('hex') === '1a45dfa3') return 'webm';
    return null;
}

// Every reference is bounded before it is sent. Photographers load 16K frames (126 MB as a
// JPEG, 268 MP): sent raw that is a ~170 MB JSON body, and no endpoint publishes a ceiling
// except Wan's (8000 px, 20 MB). No model here outputs past 4096 on a side, so a reference
// bigger than that buys nothing. A model billed per input megapixel caps lower
// (`cloud.inputMaxPixels`: FLUX-2 pro/max, a 2048^2 reference billed 4x a 1 MP one).
const REF_MAX_PIXELS = 4096 * 4096;
const REF_MAX_BYTES = 10 * 1024 * 1024;

/** A reference's bytes: untouched when small, else one upright JPEG within the caps. */
async function _readReference(file, maxPixels = REF_MAX_PIXELS) {
    const bytes = await fs.readFile(file);
    const img = () => sharp(bytes, { limitInputPixels: false });
    const { width, height, orientation } = await img().metadata();
    if (!width || !height) return bytes;
    const area = width * height;
    if (area <= maxPixels && bytes.length <= REF_MAX_BYTES) return bytes;
    const scale = Math.min(1, Math.sqrt(maxPixels / area));
    // metadata is the STORED size; EXIF 5-8 turn it a quarter, and rotate() runs first.
    const [w, h] = orientation >= 5 ? [height, width] : [width, height];
    return img().rotate()
        .resize(Math.floor(w * scale), Math.floor(h * scale), { fit: 'inside' })
        .flatten({ background: '#ffffff' })
        .jpeg({ quality: 92 }).toBuffer();
}

router.post('/deepinfra/generate', async (req, res) => {
    const { modelId, operation = '', prompt = '', seed = null, width = 0, height = 0, imagePaths = [], batch = 1,
        ratioLabel = '', qualityTier = '', duration = 0, estimateUsd = 0 } = req.body || {};
    const refs = (Array.isArray(imagePaths) ? imagePaths : []).filter(p => typeof p === 'string' && p);

    const model = MODELS.find(m => m.id === modelId);
    if (!model?.provider || !model.cloud?.endpointId) {
        return _fail(res, 'PROVIDER_ERROR', 'That model does not run in the cloud.', 400);
    }
    // An op that needs a picture and arrives without one must not run: the endpoint
    // takes the image as OPTIONAL, so it would bill a text-to-image from the prompt alone
    // and hand it back as the "edit". Measured 2026-09-25: five paid edits that never
    // saw their reference, with no error anywhere.
    if ((getCommand(operation)?.requiresImages || 0) > refs.length) {
        return _fail(res, 'PROVIDER_ERROR', 'This edit needs a reference image, and none arrived.', 400);
    }

    const { resolveConnection } = await engines();
    const { profile, key } = await resolveConnection(PROFILE_ID, ask);
    if (!profile || !profile.baseURL) return _fail(res, 'NO_PROFILE', 'The DeepInfra connection has no address saved.');
    // The main process nulls the key when the profile's bound base URL no longer
    // matches, so a repointed profile reads as keyless here. That is the right answer,
    // not an error: the saved key was for a different host.
    if (!key) return _fail(res, 'NO_KEY', 'No DeepInfra key is saved.');

    // The estimate is the renderer's price-tag figure. Trusting it is safe in one direction
    // only, which is the only direction it is used: it can refuse a run, never permit one.
    if (Number(estimateUsd) > 0) {
        const refusal = _creditRefusal(Number(estimateUsd), await _readAccountRoom(key));
        if (refusal) {
            logger.info('system', `deepinfra generate: ${model.id} refused before dispatch (${refusal.code})`);
            return _fail(res, refusal.code, refusal.message);
        }
    }

    const body = { prompt, ...(model.cloud.body || {}) };
    if (Number.isFinite(seed) && seed >= 0) body.seed = seed;

    // Several references for a model whose endpoint takes ONE: collage them (MPI-919).
    // The ratio then comes from image 1, because the model follows its input's shape and
    // the sheet's shape is not the picture the user is editing.
    let sheet = null;
    if (refs.length > 1 && model.capabilities?.referenceCollage && model.cloud.imageField) {
        try {
            sheet = await buildCollage(refs);
        } catch (err) {
            return _fail(res, 'PROVIDER_ERROR', 'The reference images could not be read.');
        }
        body.prompt = sheet.preamble + prompt;
    }

    // The size, and the batch, in whatever shape THIS endpoint speaks — pixels, a size
    // string, a ratio label, or a resolution tier plus a ratio plus a duration. All four
    // exist across the sixteen shipped models (see js/data/modelConstants/deepinfraSizing.js),
    // so the translation is table-driven off the price snapshot rather than branched here.
    //
    // Re-derived server-side rather than trusted from the client for the same reason the
    // batch always was: every one of these fields moves the bill, and the renderer is not
    // the authority on spending. The caps are the endpoint's own published maxima.
    Object.assign(body, buildSizeFields(model.cloud.endpointId, sheet
        ? { width: sheet.width, height: sheet.height, qualityTier, duration, batch }
        : { width, height, ratioLabel, qualityTier, duration, batch }));
    // Most endpoints take the picture as a data URL. Wan 3.0 takes a LIST of typed
    // media (`[{ type: 'first_frame', url }]`), named by `cloud.imageMediaType`; a bare
    // string there is a 422 (measured 2026-09-25), so Wan's i2v never ran before this.
    // FLUX-2 pro/max take bare base64 (`cloud.imageBareBase64`): BFL cannot decode a data
    // URL and answers a 500. The data URL names the file's REAL type, sniffed from its bytes.
    const placeImage = (bytes, field = model.cloud.imageField) => {
        const b64 = bytes.toString('base64');
        const value = model.cloud.imageBareBase64 ? b64 : `data:${IMAGE_MIME[_extOf(bytes)] || 'image/png'};base64,${b64}`;
        body[field] = model.cloud.imageMediaType
            ? [{ type: model.cloud.imageMediaType, url: value }]
            : value;
    };
    // Native multi-reference (MPI-919): reference N in the endpoint's Nth numbered field,
    // in strip order. Any other model sends image 1 alone, exactly as before.
    const fields = model.cloud.imageFields || (model.cloud.imageField ? [model.cloud.imageField] : []);
    if (sheet) {
        placeImage(sheet.jpeg);
    } else {
        try {
            for (let i = 0; i < Math.min(refs.length, fields.length); i++) {
                placeImage(await _readReference(refs[i], model.cloud.inputMaxPixels), fields[i]);
            }
        } catch (err) {
            return _fail(res, 'PROVIDER_ERROR', 'The reference image could not be read.');
        }
    }

    let upstream;
    try {
        upstream = await fetch(`${INFERENCE_BASE}/${model.cloud.endpointId}`, {
            method: 'POST',
            headers: { Authorization: `bearer ${key}`, 'Content-Type': 'application/json' },
            body: JSON.stringify(body),
            signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
        });
    } catch (err) {
        // Rebuilt deliberately: an upstream error object can carry the request, and the
        // request carries the key.
        logger.warn('system', `deepinfra generate: transport failure for ${model.id}`);
        return _fail(res, 'PROVIDER_ERROR', 'DeepInfra could not be reached.');
    }

    let json = null;
    try { json = await upstream.json(); } catch (_) { /* answered below as a provider error */ }

    if (!upstream.ok || !json) {
        // Status only, plus a wrapped provider status and its HOST (never the URL path, which
        // names the provider's project). The body is not logged and not returned — see the header.
        const detail = typeof json?.detail === 'string' ? json.detail : '';
        const wrapped = _wrappedStatus(detail);
        const host = wrapped && /Request to https?:\/\/([^/\s]+)/.exec(detail)?.[1];
        logger.warn('system', `deepinfra generate: ${model.id} answered HTTP ${upstream.status}`
            + (wrapped ? ` (provider ${host || '?'} said ${wrapped})` : ''));
        return _fail(res, _codeForStatus(upstream.status, detail), null);
    }

    const cost = {
        usd: Number(json?.inference_status?.cost) || 0,
        model: model.cloud.endpointId,
        at: new Date().toISOString(),
    };

    await fs.ensureDir(OUTPUT_DIR);
    _sweepOutputs().catch(() => {});
    const ownPort = Number(process.env.CUBRIC_PORT) || 3000;
    // `?filename=` is load-bearing: save-generation derives the extension from it and
    // defaults to png, which would mislabel every JPEG this route ever writes.
    const served = (id, ext) => `http://127.0.0.1:${ownPort}/deepinfra/output/${id}.${ext}?filename=${id}.${ext}`;
    const viewUrls = [];

    const outputs = _outputsOf(json);
    if (!outputs.length) {
        // A 200 with no image IS the Gemini family's content refusal.
        logger.warn('system', `deepinfra generate: ${model.id} returned no media`);
        return _fail(res, 'CONTENT_FILTERED', null);
    }
    // ONE OUTPUT PER OUTPUT ASKED FOR (MPI-875). The provider is under no obligation
    // to hand back the count it was given, and on 2026-09-21 `google/nano-banana-2`
    // answered a single-image request with the SAME generation twice — byte-identical
    // pixels, a fresh C2PA signature on each copy, and one charge for the pair. Every
    // extra copy becomes its own gallery card downstream (`generationService` builds
    // one card per url) carrying the whole call's cost, so the count is kept here,
    // where it was decided. Header contract: "N outputs, ONE call, ONE bill".
    const wanted = Math.max(1, Math.min(batchFieldFor(model.cloud.endpointId)?.max || 1,
        Number(batch) || 1));
    if (outputs.length > wanted) {
        // Counts only. The body is never logged — see the file header.
        logger.warn('system', `deepinfra generate: ${model.id} returned ${outputs.length} outputs for ${wanted} asked; keeping ${wanted}`);
    }
    for (const raw of outputs.slice(0, wanted)) {
        // A link is fetched here so the project save path only ever talks to this app.
        let bytes;
        try {
            bytes = await _bytesOf(raw);
        } catch (err) {
            logger.warn('system', `deepinfra generate: ${model.id} output fetch failed`);
            return _fail(res, 'PROVIDER_ERROR', 'The result was generated but could not be downloaded.');
        }
        // Bytes that are no picture or clip we know are never saved as one. Seedream's
        // links were base64-decoded into 121-byte "PNGs" until 2026-09-25: billed, and a
        // broken card with no error anywhere.
        const ext = _extOf(bytes);
        if (!ext) {
            logger.warn('system', `deepinfra generate: ${model.id} answered ${bytes.length} bytes of no known media type`);
            return _fail(res, 'PROVIDER_ERROR', 'The provider answered with something that is not a picture or a clip.');
        }
        const id = crypto.randomUUID();
        await fs.writeFile(path.join(OUTPUT_DIR, `${id}.${ext}`), bytes);
        viewUrls.push(served(id, ext));
    }

    res.json({
        ok: true,
        viewUrls,
        cost,
        seed: Number.isFinite(json?.seed) ? json.seed : seed,
    });
});

/**
 * GET /deepinfra/account — this month's spend and what is left (MPI-855), for the Remote
 * panel. Fired by the user's click, never on open: it is a billing read on their key.
 *   -> { ok:true, spentUsd, balanceUsd, limitRoomUsd, limitUsd }   null = no such stop
 *   -> { ok:false, error:{ code, message } }   NO_PROFILE | NO_KEY | PROVIDER_ERROR
 */
router.get('/deepinfra/account', async (req, res) => {
    const { resolveConnection } = await engines();
    const { profile, key } = await resolveConnection(PROFILE_ID, ask);
    if (!profile || !profile.baseURL) return _fail(res, 'NO_PROFILE', 'The DeepInfra connection has no address saved.');
    if (!key) return _fail(res, 'NO_KEY', 'No DeepInfra key is saved.');
    const checklist = await _readChecklist(key);
    if (!checklist) {
        logger.warn('system', 'deepinfra account: the billing read failed');
        return _fail(res, 'PROVIDER_ERROR', 'DeepInfra did not answer the billing read.');
    }
    res.json({ ok: true, ..._accountSummary(checklist) });
});

/**
 * GET /deepinfra/output/:name — the bytes, for `save-generation` to stream into the
 * project. NOT deleted on serve (see OUTPUT_KEEP_MS): `_sweepOutputs` ages them out.
 */
router.get('/deepinfra/output/:name', async (req, res) => {
    // Basename only — a name is an id this route minted, never a path.
    const name = path.basename(String(req.params.name || ''));
    const file = path.join(OUTPUT_DIR, name);
    if (!name || !await fs.pathExists(file)) return res.status(404).end();
    res.sendFile(file, (err) => {
        if (err) logger.warn('system', `deepinfra output ${name} could not be served`);
    });
});

module.exports = router;
module.exports._accountRoom = _accountRoom;
module.exports._creditRefusal = _creditRefusal;
module.exports._accountSummary = _accountSummary;
module.exports._outputsOf = _outputsOf;
module.exports._bytesOf = _bytesOf;
module.exports._extOf = _extOf;
module.exports._sweepOutputs = _sweepOutputs;
module.exports._readReference = _readReference;
module.exports._codeForStatus = _codeForStatus;
