/**
 * routes/deepinfra.js — the one place a paid cloud generation actually happens (MPI-851).
 *
 * The renderer cannot make this call itself, and must not: the API key lives in the main
 * process and there is no channel that hands it out (set / has / clear only, by design).
 * So the renderer asks for a generation by MODEL ID and this route resolves everything
 * else — which endpoint, which key, which body. Taking the endpoint id from the client
 * would let any renderer path spend the user's money at any model on DeepInfra's
 * catalogue; taking the model id means the ModelDef is the whitelist.
 *
 * THE NATIVE ROUTE, NOT THE OPENAI-COMPATIBLE ONE. `POST /v1/inference/<model>` returns
 * `inference_status.cost` — the true figure for this call. The OpenAI-shaped routes
 * return `created` and `data` and nothing else, so dispatching there would lose the cost
 * entirely and leave the spend readout summing estimates.
 *
 * BYTES, NOT A LINK. DeepInfra hands images back as base64 (and video as a URL), while
 * `save-generation` wants something it can stream and derives the file extension from a
 * `?filename=`. So the bytes land in a scratch file here and the response points at
 * `GET /deepinfra/output/:id`, which is a real http URL with a real extension — the save
 * path is then completely unchanged. It matters that the extension is right rather than
 * assumed: the same family returns JPEG on one tier and PNG on another.
 *
 * WHAT NEVER LEAVES THIS FILE: the key, and the upstream response body. A DeepInfra
 * error body can carry account detail, and `routes/secretRedaction.js` is five regexes
 * for key-shaped strings — it cannot scrub a name or an address. So failures are
 * answered as a CODE plus a message this file wrote, and nothing upstream reaches
 * `logger.*`, which is exfiltratable by design.
 *
 *   POST /deepinfra/generate  { modelId, operation, prompt, seed, width, height,
 *                               ratioLabel, qualityTier, duration, imagePath, batch }
 *     -> { ok:true, viewUrls:[…], cost:{ usd, model, at }, seed }
 *        The size arrives in every currency the caller knows and `buildSizeFields`
 *        picks the one THIS endpoint takes — pixels, a 'WIDTHxHEIGHT' string, a bare
 *        ratio label, or a resolution tier plus a ratio plus a duration. `batch` is the
 *        provider's own native count where it has one (`num_images`, or Veo's
 *        `sample_count`): N outputs, ONE call, ONE bill.
 *     -> { ok:false, error:{ code, message } }   NO_KEY | NO_PROFILE | NO_CREDIT |
 *                                                CONTENT_FILTERED | PROVIDER_ERROR
 *   GET  /deepinfra/output/:id  -> the generated bytes, once, then they are swept.
 */

'use strict';

const express = require('express');
const fs = require('fs-extra');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const router = express.Router();
const logger = require('./logger');
const { ask } = require('./forkBridge');
const { MODELS } = require('../js/data/modelConstants/models.js');
const { buildSizeFields, batchFieldFor } = require('../js/data/modelConstants/deepinfraSizing.js');

const PROFILE_ID = 'deepinfra';
const INFERENCE_BASE = 'https://api.deepinfra.com/v1/inference';
// Long, because a 1080p video clip legitimately takes minutes — but finite, because a
// Node fetch gives up at 300 s waiting for HEADERS whatever an AbortSignal says, and a
// silent hang would hold the cloud lane open forever.
const REQUEST_TIMEOUT_MS = 280000;

// `services/llmEngines.mjs` is ESM and this router is CJS — same dynamic-import bridge
// routes/llm.js uses, and the same `resolveConnection` behind it, so there is exactly
// one key resolution in the app.
let _enginesPromise = null;
function engines() {
    if (!_enginesPromise) _enginesPromise = import('../services/llmEngines.mjs');
    return _enginesPromise;
}

/** Scratch dir for generated bytes on their way into a project. */
const OUTPUT_DIR = path.join(os.tmpdir(), 'cubric-deepinfra');

const _fail = (res, code, message, status = 200) =>
    res.status(status).json({ ok: false, error: { code, message } });

/** Map an upstream status to a code the UI has copy for. Never echo the body. */
function _codeForStatus(status) {
    if (status === 401 || status === 403) return 'NO_KEY';
    if (status === 402) return 'NO_CREDIT';
    // The Gemini family answers a refused prompt with a 500 and no image. It is a
    // frequent path for this product's material, not an edge case.
    if (status === 400 || status === 422 || status === 500) return 'CONTENT_FILTERED';
    return 'PROVIDER_ERROR';
}

/** Every base64 image the model answered with, each with its own extension. */
function _extractImages(body) {
    const list = body?.images || body?.image || body?.output
        || (Array.isArray(body?.data) ? body.data.map(d => d?.b64_json) : null) || [];
    return list.filter(raw => typeof raw === 'string' && raw).map((raw) => {
        const dataUri = raw.match(/^data:image\/([a-z0-9+.-]+);base64,(.*)$/i);
        if (dataUri) {
            const kind = dataUri[1].toLowerCase();
            return { base64: dataUri[2], ext: kind === 'jpeg' ? 'jpg' : kind };
        }
        // Bare base64: sniff the magic bytes rather than assume PNG. A `.png` holding
        // JPEG bytes opens fine in most viewers and fails somewhere far away from here —
        // measured on the first real generation, which came back JPEG.
        const buf = Buffer.from(raw, 'base64');
        const ext = buf.slice(0, 3).toString('hex') === 'ffd8ff' ? 'jpg'
            : (buf.slice(0, 4).toString('ascii') === 'RIFF' ? 'webp' : 'png');
        return { base64: raw, ext };
    });
}

router.post('/deepinfra/generate', async (req, res) => {
    const { modelId, prompt = '', seed = null, width = 0, height = 0, imagePath = null, batch = 1,
        ratioLabel = '', qualityTier = '', duration = 0 } = req.body || {};

    const model = MODELS.find(m => m.id === modelId);
    if (!model?.provider || !model.cloud?.endpointId) {
        return _fail(res, 'PROVIDER_ERROR', 'That model does not run in the cloud.', 400);
    }

    const { resolveConnection } = await engines();
    const { profile, key } = await resolveConnection(PROFILE_ID, ask);
    if (!profile || !profile.baseURL) return _fail(res, 'NO_PROFILE', 'The DeepInfra connection has no address saved.');
    // The main process nulls the key when the profile's bound base URL no longer
    // matches, so a repointed profile reads as keyless here. That is the right answer,
    // not an error: the saved key was for a different host.
    if (!key) return _fail(res, 'NO_KEY', 'No DeepInfra key is saved.');

    const body = { prompt, ...(model.cloud.body || {}) };
    if (Number.isFinite(seed) && seed >= 0) body.seed = seed;

    // The size, and the batch, in whatever shape THIS endpoint speaks — pixels, a size
    // string, a ratio label, or a resolution tier plus a ratio plus a duration. All four
    // exist across the sixteen shipped models (see js/data/modelConstants/deepinfraSizing.js),
    // so the translation is table-driven off the price snapshot rather than branched here.
    //
    // Re-derived server-side rather than trusted from the client for the same reason the
    // batch always was: every one of these fields moves the bill, and the renderer is not
    // the authority on spending. The caps are the endpoint's own published maxima.
    Object.assign(body, buildSizeFields(model.cloud.endpointId, {
        width, height, ratioLabel, qualityTier, duration, batch,
    }));
    if (imagePath && model.cloud.imageField) {
        try {
            const bytes = await fs.readFile(imagePath);
            body[model.cloud.imageField] = `data:image/png;base64,${bytes.toString('base64')}`;
        } catch (err) {
            return _fail(res, 'PROVIDER_ERROR', 'The reference image could not be read.');
        }
    }

    let upstream;
    try {
        upstream = await fetch(`${INFERENCE_BASE}/${model.cloud.endpointId}`, {
            method: 'POST',
            headers: { Authorization: `bearer ${key}`, 'Content-Type': 'application/json' },
            body: JSON.stringify(body),
            signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
        });
    } catch (err) {
        // Rebuilt deliberately: an upstream error object can carry the request, and the
        // request carries the key.
        logger.warn('system', `deepinfra generate: transport failure for ${model.id}`);
        return _fail(res, 'PROVIDER_ERROR', 'DeepInfra could not be reached.');
    }

    let json = null;
    try { json = await upstream.json(); } catch (_) { /* answered below as a provider error */ }

    if (!upstream.ok || !json) {
        // Status only. The body is not logged and not returned — see the file header.
        logger.warn('system', `deepinfra generate: ${model.id} answered HTTP ${upstream.status}`);
        return _fail(res, _codeForStatus(upstream.status), null);
    }

    const cost = {
        usd: Number(json?.inference_status?.cost) || 0,
        model: model.cloud.endpointId,
        at: new Date().toISOString(),
    };

    await fs.ensureDir(OUTPUT_DIR);
    const ownPort = Number(process.env.CUBRIC_PORT) || 3000;
    // `?filename=` is load-bearing: save-generation derives the extension from it and
    // defaults to png, which would mislabel every JPEG this route ever writes.
    const served = (id, ext) => `http://127.0.0.1:${ownPort}/deepinfra/output/${id}.${ext}?filename=${id}.${ext}`;
    const viewUrls = [];

    const videoUrl = json?.video_url || json?.output?.video_url || null;
    if (videoUrl) {
        const id = crypto.randomUUID();
        // Video comes back as a link rather than base64. Fetched here so the project
        // save path only ever talks to this app.
        try {
            const clip = await fetch(videoUrl, { signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS) });
            if (!clip.ok) throw new Error(`HTTP ${clip.status}`);
            const ext = (new URL(videoUrl).pathname.split('.').pop() || 'mp4').toLowerCase();
            await fs.writeFile(path.join(OUTPUT_DIR, `${id}.${ext}`), Buffer.from(await clip.arrayBuffer()));
            viewUrls.push(served(id, ext));
        } catch (err) {
            logger.warn('system', `deepinfra generate: ${model.id} clip fetch failed`);
            return _fail(res, 'PROVIDER_ERROR', 'The clip was generated but could not be downloaded.');
        }
    } else {
        const images = _extractImages(json);
        if (!images.length) {
            // A 200 with no image IS the Gemini family's content refusal.
            logger.warn('system', `deepinfra generate: ${model.id} returned no media`);
            return _fail(res, 'CONTENT_FILTERED', null);
        }
        // ONE OUTPUT PER OUTPUT ASKED FOR (MPI-875). The provider is under no obligation
        // to hand back the count it was given, and on 2026-09-21 `google/nano-banana-2`
        // answered a single-image request with the SAME generation twice — byte-identical
        // pixels, a fresh C2PA signature on each copy, and one charge for the pair. Every
        // extra copy becomes its own gallery card downstream (`generationService` builds
        // one card per url) carrying the whole call's cost, so the count is kept here,
        // where it was decided. Header contract: "N outputs, ONE call, ONE bill".
        const wanted = Math.max(1, Math.min(batchFieldFor(model.cloud.endpointId)?.max || 1,
            Number(batch) || 1));
        if (images.length > wanted) {
            // Counts only. The body is never logged — see the file header.
            logger.warn('system', `deepinfra generate: ${model.id} returned ${images.length} outputs for ${wanted} asked; keeping ${wanted}`);
        }
        for (const image of images.slice(0, wanted)) {
            const id = crypto.randomUUID();
            await fs.writeFile(path.join(OUTPUT_DIR, `${id}.${image.ext}`), Buffer.from(image.base64, 'base64'));
            viewUrls.push(served(id, image.ext));
        }
    }

    res.json({
        ok: true,
        viewUrls,
        cost,
        seed: Number.isFinite(json?.seed) ? json.seed : seed,
    });
});

/**
 * GET /deepinfra/output/:name — the bytes, for `save-generation` to stream into the
 * project. Deleted once served: the project copy is the durable one, and these are
 * generated images sitting in a world-readable temp dir.
 */
router.get('/deepinfra/output/:name', async (req, res) => {
    // Basename only — a name is an id this route minted, never a path.
    const name = path.basename(String(req.params.name || ''));
    const file = path.join(OUTPUT_DIR, name);
    if (!name || !await fs.pathExists(file)) return res.status(404).end();
    res.sendFile(file, (err) => {
        if (err) logger.warn('system', `deepinfra output ${name} could not be served`);
        fs.remove(file).catch(() => {});
    });
});

module.exports = router;
