"""MPI-1041 A3: build the Flow's own Qwen-Image 2.1 edit graph, `comfy_workflows/raw/flow_character_sheet_edit_qwen.json`
(LiteGraph), by PRUNING a copy of the model graph `comfy_workflows/raw/qwen_image_2_1.json` down to its edit path
(Input_wf_type 4, no mask) - the model's own raw and runtime graphs are only READ, never edited.

Kept as the donor has them (same ids, same widget values): UNETLoader 1 -> QwenImage21Cache 2, CLIPLoader 3, VAELoader 4,
Input_Positive 5, Input_Seed 8, Input_Image 11, TextEncodeQwenImage21 30, KSampler 33, VAEDecode 34, SplitImageWithAlpha 46,
MpiClearVram 115, Output_Image 35. Dropped: the mask / inpaint / detail / upscale / control / tile branches, the 8 reference
switches, the width / height / wf_type / LoRA / style-rack nodes, the style-trigger concat (selector 0 = no style, so the
prompt reaches the encoder without the trailing " " the concat added).
What changes from the bench path (validation.md batch 9, qba.py qwen21): node 30 `resolution` 0 is BAKED (the sheet's own
size; the node itself rounds each reference to a multiple of 32), the picture goes straight into image_1, alpha is dropped
(the 2.1 VAE decodes RGBA, alpha 253-255 on the bench outputs), and the result is stretched back to the INPUT size (a no-op
for a sheet already a multiple of 32; <= 1.7% for any other). Donors for the two nodes the model graph lacks: ImageScale
and the Note from `flow_character_sheet_from_images.json`.
Only app-touched titles: Input_Image, Input_Positive, Input_Seed, Output_Image. The prompt is whatever the app writes.
Layout is new (the model graph's is a 6000 px scatter); ids are the donor's so a node is traceable to qwen_image_2_1.json.
usage: build_edit_graph_qwen.py [out.json]   (default: the raw file; same bytes every run)"""
import copy, json, os, sys, uuid

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '../../../../../..'))
RAW = os.path.join(REPO, 'comfy_workflows', 'raw')
SRC = os.path.join(RAW, 'qwen_image_2_1.json')
DONOR2 = os.path.join(RAW, 'flow_character_sheet_from_images.json')
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(RAW, 'flow_character_sheet_edit_qwen.json')


def load(path, exact=False):
    text = open(path, encoding='utf-8').read()
    g = json.loads(text)
    if exact:  # raw/ files are LF, 2-space, ensure_ascii=False, trailing newline (bench-editing.md): prove the serialiser
        assert json.dumps(g, indent=2, ensure_ascii=False) + '\n' == text, f'{path} does not round-trip: fix the serialiser'
    return {n['id']: n for n in g['nodes']}


Q, D2 = load(SRC, exact=True), load(DONOR2)  # the model graph is the format donor; the second one only lends two nodes
NODES, LINKS = {}, []


def take(donor, nid, new_id=None, pos=(0, 0), size=None, title=None, widgets=None):
    """Deep-copy a donor node, unplug it, re-stamp what is ours. Never a hand-written node."""
    n = copy.deepcopy(donor[nid])
    n['id'] = new_id or nid
    n['pos'], n['flags'], n['mode'] = list(pos), {}, 0
    if size:
        n['size'] = list(size)
    if title:
        n['title'] = title
    for i in n.get('inputs', []):
        i['link'] = None
    for o in n.get('outputs', []):
        o['links'] = []
    if widgets is not None:
        n['widgets_values'] = widgets
        if 'widgets_values_named' in n:  # same keys, new values (none of the nodes we re-stamp has a control_after_generate)
            assert len(n['widgets_values_named']) == len(widgets), n['id']
            n['widgets_values_named'] = dict(zip(n['widgets_values_named'], widgets))
    NODES[n['id']] = n
    return n


def link(src, out, dst, inp):
    s, d = NODES[src], NODES[dst]
    so = next(i for i, o in enumerate(s['outputs']) if o['name'] == out)
    di = next(i for i, x in enumerate(d['inputs']) if x['name'] == inp)
    assert d['inputs'][di]['link'] is None, (dst, inp)
    typ = s['outputs'][so]['type']
    if typ == '*':
        typ = 'IMAGE'
    lid = len(LINKS) + 1
    LINKS.append([lid, src, so, dst, di, typ])
    s['outputs'][so]['links'].append(lid)
    d['inputs'][di]['link'] = lid


NOTE = (
    "MPI-1041 Character Sheet Editor - the Qwen-Image 2.1 edit graph (generated by build_edit_graph_qwen.py, pruned from "
    "qwen_image_2_1.json's edit path).\n\n"
    "The app fills: Input_Image (the finished 3-panel sheet), Input_Positive (the WHOLE prompt - the Flow's builder writes it, "
    "nothing is baked here), Input_Seed.\n\n"
    "Size: TextEncodeQwenImage21 resolution is baked 0 = the sheet at its own size, each side rounded to a multiple of 32, and "
    "the canvas follows picture 1, so the edit is not resized at all on a 32-multiple sheet. The result is stretched back to "
    "the INPUT size (a no-op at 1792x1120).\n\n"
    "Alpha is dropped: the 2.1 VAE decodes RGBA. Research licence: the pictures are non-commercial.")

take(D2, 1, new_id=129, pos=(-560, -60), size=(500, 520), widgets=[NOTE])
take(Q, 11, pos=(0, 0), widgets=['None', 'alpha', True, '', 'image'])  # Input_Image; block when empty (the sheet is required)
take(Q, 5, pos=(0, 290), widgets=[''])  # Input_Positive: the app writes the whole prompt
take(Q, 8, pos=(0, 540))  # Input_Seed (value 42, the app overrides)
take(Q, 1, pos=(0, 660))  # UNETLoader qwen_image_2.1_int8_convrot
take(Q, 2, pos=(330, 660))  # QwenImage21Cache auto / default
take(Q, 3, pos=(0, 800))  # CLIPLoader qwen3vl_8b_int8_convrot
take(Q, 4, pos=(0, 960))  # VAELoader qwen_image_2.1_vae_bf16
take(Q, 30, pos=(480, 0), size=(400, 366), title='Qwen edit: picture 1 = the sheet, own size (resolution 0)',
     widgets=['', '', 0])  # prompt / negative_prompt arrive by link or stay '' ; resolution 0 BAKED
take(Q, 33, pos=(940, 0))  # KSampler 30 steps cfg 1 euler simple denoise 1
take(Q, 34, pos=(1270, 0))  # VAEDecode
take(Q, 46, pos=(1270, 100), title='drop alpha (2.1 VAE decodes RGBA)')
take(D2, 35, new_id=128, pos=(1500, 0), size=(270, 130), title="back to the sheet's own size",
     widgets=['bicubic', 512, 512, 'disabled'])  # bicubic = exact identity at the same size; width / height by link
take(Q, 115, pos=(1500, 200))  # MpiClearVram, UPSTREAM of the capture title
take(Q, 35, pos=(1800, 0), size=(420, 300))  # Output_Image

assert NODES[11]['widgets_values_named']['block_if_empty'] is True
assert NODES[30]['widgets_values_named']['resolution'] == 0

link(1, 'MODEL', 2, 'model')
link(2, 'MODEL', 33, 'model')
link(3, 'CLIP', 30, 'clip')
link(4, 'VAE', 30, 'vae')
link(11, 'image', 30, 'images.image_1')
link(5, 'Text', 30, 'prompt')
link(30, 'positive', 33, 'positive')
link(30, 'negative', 33, 'negative')
link(30, 'latent', 33, 'latent_image')
link(8, 'int', 33, 'seed')
link(33, 'LATENT', 34, 'samples')
link(4, 'VAE', 34, 'vae')
link(34, 'IMAGE', 46, 'image')
link(46, 'IMAGE', 128, 'image')
link(11, 'width', 128, 'width')
link(11, 'height', 128, 'height')
link(128, 'IMAGE', 115, 'passthrough')
link(115, 'passthrough', 35, 'images')

# execution order = topological, so the file reads left to right
order = [129, 11, 5, 8, 1, 2, 3, 4, 30, 33, 34, 46, 128, 115, 35]
assert sorted(order) == sorted(NODES)
for k, nid in enumerate(order):
    NODES[nid]['order'] = k

# ---- checks: what the file CONTAINS (the app cannot see most of these slips)
titles = {n['title'] for n in NODES.values() if n.get('title')}
app = sorted(t for t in titles if t.startswith(('Input_', 'Output_')))
assert app == ['Input_Image', 'Input_Positive', 'Input_Seed', 'Output_Image'], app
for l in LINKS:
    lid, s, so, d, di, typ = l
    assert lid in NODES[s]['outputs'][so]['links'] and NODES[d]['inputs'][di]['link'] == lid, l
assert sum(len(o['links']) for n in NODES.values() for o in n.get('outputs', [])) == len(LINKS)
assert sum(1 for n in NODES.values() for i in n.get('inputs', []) if i['link'] is not None) == len(LINKS)
up, stack = set(), [35]  # every node except the Note feeds Output_Image
while stack:
    cur = stack.pop()
    if cur in up:
        continue
    up.add(cur)
    stack += [l[1] for l in LINKS if l[3] == cur]
assert up == set(NODES) - {129}, sorted(set(NODES) - {129} - up)
assert not [n for n in NODES.values() if n.get('mode')], 'a muted / bypassed node ships as a pass-through'

graph = {
    'id': str(uuid.uuid5(uuid.NAMESPACE_URL, 'cubric-studio/flow_character_sheet_edit_qwen')), 'revision': 0,
    'last_node_id': max(NODES), 'last_link_id': len(LINKS),
    'nodes': [NODES[i] for i in sorted(NODES)], 'links': LINKS, 'groups': [], 'config': {},
    'extra': {'frontendVersion': '1.53.10', 'ds': {'scale': 0.6, 'offset': [700, 200]}}, 'version': 0.4}
with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
    f.write(json.dumps(graph, indent=2, ensure_ascii=False) + '\n')
print('wrote', OUT, len(NODES), 'nodes', len(LINKS), 'links')
